/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosIndexRouteImport } from './routes/produtos.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as ProdutosSlugIndexRouteImport } from './routes/produtos.$slug.index'
import { Route as ProdutosSlugTipoRouteImport } from './routes/produtos.$slug.$tipo'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosIndexRoute = ProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)
const ProdutosSlugIndexRoute = ProdutosSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProdutosSlugRoute,
} as any)
const ProdutosSlugTipoRoute = ProdutosSlugTipoRouteImport.update({
  id: '/$tipo',
  path: '/$tipo',
  getParentRoute: () => ProdutosSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/produtos/$slug': typeof ProdutosSlugRouteWithChildren
  '/produtos/': typeof ProdutosIndexRoute
  '/produtos/$slug/$tipo': typeof ProdutosSlugTipoRoute
  '/produtos/$slug/': typeof ProdutosSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/servicos': typeof ServicosRoute
  '/produtos': typeof ProdutosIndexRoute
  '/produtos/$slug/$tipo': typeof ProdutosSlugTipoRoute
  '/produtos/$slug': typeof ProdutosSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/produtos/$slug': typeof ProdutosSlugRouteWithChildren
  '/produtos/': typeof ProdutosIndexRoute
  '/produtos/$slug/$tipo': typeof ProdutosSlugTipoRoute
  '/produtos/$slug/': typeof ProdutosSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/empresa'
    | '/produtos'
    | '/servicos'
    | '/produtos/$slug'
    | '/produtos/'
    | '/produtos/$slug/$tipo'
    | '/produtos/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/empresa'
    | '/servicos'
    | '/produtos'
    | '/produtos/$slug/$tipo'
    | '/produtos/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/empresa'
    | '/produtos'
    | '/servicos'
    | '/produtos/$slug'
    | '/produtos/'
    | '/produtos/$slug/$tipo'
    | '/produtos/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/': {
      id: '/produtos/'
      path: '/'
      fullPath: '/produtos/'
      preLoaderRoute: typeof ProdutosIndexRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/$slug/': {
      id: '/produtos/$slug/'
      path: '/'
      fullPath: '/produtos/$slug/'
      preLoaderRoute: typeof ProdutosSlugIndexRouteImport
      parentRoute: typeof ProdutosSlugRoute
    }
    '/produtos/$slug/$tipo': {
      id: '/produtos/$slug/$tipo'
      path: '/$tipo'
      fullPath: '/produtos/$slug/$tipo'
      preLoaderRoute: typeof ProdutosSlugTipoRouteImport
      parentRoute: typeof ProdutosSlugRoute
    }
  }
}

interface ProdutosSlugRouteChildren {
  ProdutosSlugTipoRoute: typeof ProdutosSlugTipoRoute
  ProdutosSlugIndexRoute: typeof ProdutosSlugIndexRoute
}

const ProdutosSlugRouteChildren: ProdutosSlugRouteChildren = {
  ProdutosSlugTipoRoute: ProdutosSlugTipoRoute,
  ProdutosSlugIndexRoute: ProdutosSlugIndexRoute,
}

const ProdutosSlugRouteWithChildren = ProdutosSlugRoute._addFileChildren(
  ProdutosSlugRouteChildren,
)

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRouteWithChildren
  ProdutosIndexRoute: typeof ProdutosIndexRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRouteWithChildren,
  ProdutosIndexRoute: ProdutosIndexRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
<<<<<<< HEAD

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
=======
>>>>>>> c7088708e7d473ddc0affa4f734a02390af123a7
