/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/empresa'
    | '/produtos'
    | '/servicos'
    | '/produtos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/empresa'
    | '/produtos'
    | '/servicos'
    | '/produtos/$slug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/empresa'
    | '/produtos'
    | '/servicos'
    | '/produtos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
